In [22]:
import gmaps
import pandas as pd

# Google developer API key
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [23]:
# Create dataframes
population_df = pd.read_csv('resources/Population_data.csv', encoding='ISO-8859-1')
population_df.head()

,CityName,Status,State(s),1990Population,2000Population,2010Population,2017EstPopulation
0,Aberdeen,Micropolitan Statistical Area,SD,"39,936","39,835","40,602","43,097"
1,Aberdeen,Micropolitan Statistical Area,WA,"64,175","67,141","72,804","72,697"
2,Abilene,Metropolitan Statistical Area,TX,"148,004","160,273","165,248","170,219"
3,Ada,Micropolitan Statistical Area,OK,"34,119","35,146","37,492","38,224"
4,Adrian,Micropolitan Statistical Area,MI,"91,476","98,970","99,892","98,623"

In [26]:
cities_df = pd.read_csv('resources/cities.csv', encoding='ISO-8859-1')
cities_df.head()

,CityName,Cloudiness,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Atlanta - Sandy Springs - Alpharetta,90,1547766900,100,33.7491,-84.3902,46.94,4.70
1,Austin - Round Rock - Georgetown,1,1547765760,39,30.2711,-97.7437,73.94,3.36
2,Baltimore - Columbia - Towson,90,1547767380,65,39.2909,-76.6108,37.04,4.27
3,Birmingham - Hoover,90,1547766900,92,33.5207,-86.8025,50.00,5.82
4,Boston - Cambridge - Newton,40,1547765760,33,42.3603,-71.0583,26.06,5.82

In [29]:
#merge on city name keeping cities_df "CityName" only
city_pop_df = pd.merge(cities_df, population_df, on="CityName")
city_pop_df

,CityName,Cloudiness,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Status,State(s),1990Population,2000Population,2010Population,2017EstPopulation
0,Atlanta - Sandy Springs - Alpharetta,90,1547766900,100,33.7491,-84.3902,46.94,4.70,Metropolitan Statistical Area,GA,"3,081,858","4,263,135","5,286,743","5,884,736"
1,Austin - Round Rock - Georgetown,1,1547765760,39,30.2711,-97.7437,73.94,3.36,Metropolitan Statistical Area,TX,"846,227","1,249,963","1,716,320","2,115,827"
2,Baltimore - Columbia - Towson,90,1547767380,65,39.2909,-76.6108,37.04,4.27,Metropolitan Statistical Area,MD,"2,382,172","2,553,137","2,710,603","2,808,175"
3,Birmingham - Hoover,90,1547766900,92,33.5207,-86.8025,50.00,5.82,Metropolitan Statistical Area,AL,"888,998","980,652","1,061,033","1,085,749"
4,Boston - Cambridge - Newton,40,1547765760,33,42.3603,-71.0583,26.06,5.82,Metropolitan Statistical Area,MA-NH,"4,133,895","4,392,533","4,552,596","4,836,531"
5,Buffalo - Cheektowaga,75,1547766000,62,42.8867,-78.8784,28.94,6.93,Metropolitan Statistical Area,NY,"1,189,340","1,170,022","1,135,617","1,136,856"
6,Charlotte - Concord - Gastonia,90,1547766900,88,35.2271,-80.8432,46.40,4.70,Metropolitan Statistical Area,NC-SC,"1,364,911","1,742,915","2,243,920","2,550,296"
7,Chicago - Naperville - Elgin,90,1547766900,92,41.8756,-87.6245,35.06,3.36,Metropolitan Statistical Area,IL-IN-WI,"8,181,939","9,098,970","9,461,541","9,533,040"
8,Cincinnati,90,1547766960,98,39.1015,-84.5125,39.02,4.70,Metropolitan Statistical Area,OH-KY-IN,"1,851,864","2,017,005","2,137,781","2,201,701"
9,Cleveland - Elyria,90,1547767680,88,41.5052,-81.6935,32.00,9.17,Metropolitan Statistical Area,OH,"2,102,207","2,148,041","2,077,271","2,058,844"
10,Columbus,90,1547766900,96,32.4610,-84.9878,57.02,1.36,Metropolitan Statistical Area,GA-AL,"278,630","293,644","308,452","316,045"
11,Columbus,90,1547766900,96,32.4610,-84.9878,57.02,1.36,Metropolitan Statistical Area,IN,"63,657","71,467","76,786","82,040"
12,Columbus,90,1547766900,96,32.4610,-84.9878,57.02,1.36,Micropolitan Statistical Area,MS,"59,308","61,596","59,779","59,186"
13,Columbus,90,1547766900,96,32.4610,-84.9878,57.02,1.36,Micropolitan Statistical Area,NE,"29,820","31,574","32,237","33,175"
14,Columbus,90,1547766900,96,32.4610,-84.9878,57.02,1.36,Metropolitan Statistical Area,OH,"1,462,268","1,675,226","1,902,001","2,078,725"
15,Dallas - Fort Worth - Arlington,1,1547766900,64,32.7763,-96.7969,57.92,5.82,Metropolitan Statistical Area,TX,"3,984,437","5,156,727","6,366,572","7,332,544"
16,Denver - Aurora - Lakewood,1,1547766900,42,39.7392,-104.9848,53.24,3.87,Metropolitan Statistical Area,CO,"1,650,489","2,179,476","2,543,592","2,888,227"
17,Detroit - Warren - Dearborn,90,1547767200,92,42.3487,-83.0568,30.92,4.70,Metropolitan Statistical Area,MI,"4,248,699","4,452,778","4,296,317","4,313,002"
18,Hartford - East Hartford - Middletown,20,1547765760,39,41.7645,-72.6909,26.60,3.53,Metropolitan Statistical Area,CT,"1,123,678","1,148,649","1,212,398","1,210,259"
19,Houston - The Woodlands - Sugar Land,1,1547766900,68,29.7589,-95.3677,69.08,6.93,Metropolitan Statistical Area,TX,"3,750,846","4,693,520","5,920,486","6,892,427"
20,Indianapolis - Carmel - Anderson,90,1547767020,96,39.7683,-86.1584,37.40,8.05,Metropolitan Statistical Area,IN,"1,424,886","1,658,439","1,888,090","2,028,614"
21,Jacksonville,1,1547766900,58,30.3322,-81.6557,59.00,2.71,Metropolitan Statistical Area,FL,"925,213","1,122,821","1,345,598","1,504,980"
22,Jacksonville,1,1547766900,58,30.3322,-81.6557,59.00,2.71,Micropolitan Statistical Area,IL,"42,041","42,166","40,906","38,800"
23,Jacksonville,1,1547766900,58,30.3322,-81.6557,59.00,2.71,Metropolitan Statistical Area,NC,"149,838","150,418","177,799","193,893"
24,Jacksonville,1,1547766900,58,30.3322,-81.6557,59.00,2.71,Micropolitan Statistical Area,TX,"41,049","46,716","50,834","52,240"
25,Kansas City,90,1547766900,91,39.0845,-94.5631,35.06,3.87,Metropolitan Statistical Area,MO-KS,"1,614,533","1,811,788","2,009,338","2,128,912"
26,Las Vegas - Henderson - Paradise,90,1547766900,82,36.1663,-115.1493,62.96,8.05,Metropolitan Statistical Area,NV,"741,368","1,375,741","1,951,269","2,204,079"
27,Los Angeles - Long Beach - Anaheim,90,1547766600,100,34.0549,-118.2445,64.04,9.17,Metropolitan Statistical Area,CA,"11,273,720","12,365,597","12,828,961","13,353,907"
28,Louisville/Jefferson County,90,1547766960,85,38.2542,-85.7595,46.04,6.93,Metropolitan Statistical Area,KY-IN,"996,186","1,090,362","1,202,712","1,261,522"
29,Memphis,90,1547767920,100,35.1490,-90.0517,55.04,6.22,Metropolitan Statistical Area,TN-MS-AR,"1,067,263","1,205,254","1,316,097","1,339,948"
30,Miami - Fort Lauderdale - Pompano Beach,75,1547765580,70,25.7743,-80.1937,71.96,6.93,Metropolitan Statistical Area,FL,"4,056,228","5,007,956","5,566,299","6,158,824"
31,Milwaukee - Waukesha,90,1547766900,91,43.0350,-87.9225,35.06,5.82,Metropolitan Statistical Area,WI,"1,432,149","1,500,788","1,555,954","1,576,236"
32,Minneapolis - St. Paul - Bloomington (Twin Cit...,1,1547766960,67,44.9773,-93.2655,21.56,6.93,Metropolitan Statistical Area,MN-WI,"2,580,685","3,016,979","3,333,632","3,585,749"
33,Nashville-Davidson - Murfreesboro - Franklin,90,1547766900,100,36.1622,-86.7744,46.40,3.36,Metropolitan Statistical Area,TN,"1,086,274","1,359,101","1,646,194","1,878,181"
34,New Orleans - Metairie,75,1547766900,87,29.9499,-90.0702,67.64,8.05,Metropolitan Statistical Area,LA,"1,285,262","1,337,740","1,189,859","1,275,762"
35,New York - Newark - Jersey City,1,1547767620,56,40.7306,-73.9867,32.00,4.54,Metropolitan Statistical Area,NY-NJ-PA,"16,863,671","18,324,459","18,896,205","19,643,082"
36,Oklahoma City,1,1547767200,70,35.4730,-97.5171,50.90,4.70,Metropolitan Statistical Area,OK,"971,042","1,095,553","1,252,991","1,383,737"
37,Orlando - Kissimmee - Sanford,75,1547765760,60,28.5421,-81.3791,69.08,4.70,Metropolitan Statistical Area,FL,"1,224,844","1,644,509","2,134,399","2,509,831"
38,Philadelphia - Camden - Wilmington,90,1547768100,60,39.9524,-75.1636,32.00,3.36,Metropolitan Statistical Area,PA-NJ-DE-MD,"5,435,550","5,686,329","5,965,693","6,096,120"
39,Phoenix - Mesa - Chandler,90,1547766900,52,33.4486,-112.0774,68.00,2.59,Metropolitan Statistical Area,AZ,"2,238,498","3,251,884","4,193,129","4,737,270"
40,Pittsburgh,90,1547766540,100,40.4417,-79.9901,30.20,4.70,Metropolitan Statistical Area,PA,"2,468,289","2,431,233","2,356,291","2,333,367"
41,Portland - Vancouver - Hillsboro,90,1547765760,56,45.5202,-122.6742,53.96,25.28,Metropolitan Statistical Area,OR-WA,"1,523,741","1,927,904","2,226,001","2,453,168"
42,Providence - Warwick,1,1547765760,37,41.8240,-71.4129,28.40,3.36,Metropolitan Statistical Area,RI-MA,"1,509,789","1,582,961","1,601,210","1,621,122"
43,Raleigh - Cary,90,1547766600,75,35.7804,-78.6391,48.74,4.09,Metropolitan Statistical Area,NC,"544,031","797,188","1,130,489","1,335,079"
44,Richmond,1,1547768100,62,49.1633,-123.1370,53.96,14.99,Micropolitan Statistical Area,IN,"71,951","71,087","69,003","66,185"
45,Richmond,1,1547768100,62,49.1633,-123.1370,53.96,14.99,Metropolitan Statistical Area,VA,"901,877","1,040,298","1,186,471","1,270,746"
46,Riverside - San Bernardino - Ontario (Inland E...,90,1547766900,89,33.9534,-117.3962,62.96,16.11,Metropolitan Statistical Area,CA,"2,588,793","3,254,799","4,224,965","4,580,670"
47,Sacramento - Roseville - Folsom,90,1547766900,67,38.5816,-121.4944,59.00,21.92,Metropolitan Statistical Area,CA,"1,506,792","1,796,822","2,149,144","2,324,884"
48,Salt Lake City,90,1547766900,64,40.7670,-111.8905,39.02,13.87,Metropolitan Statistical Area,UT,"752,557","939,169","1,087,808","1,203,105"
49,San Antonio - New Braunfels,0,1547766000,77,-33.5809,-71.6133,68.00,4.70,Metropolitan Statistical Area,TX,"1,407,745","1,711,578","2,142,516","2,473,974"
50,San Diego - Chula Vista - Carlsbad,90,1547767080,92,32.7174,-117.1628,62.96,11.41,Metropolitan Statistical Area,CA,"2,498,016","2,813,839","3,095,342","3,337,685"
51,San Francisco - Oakland - Berkeley,90,1547766900,64,37.7793,-122.4193,60.80,10.29,Metropolitan Statistical Area,CA,"3,711,756","4,123,734","4,335,573","4,727,357"
52,San Jose - Sunnyvale - Santa Clara,64,1547768054,78,15.7917,120.9891,71.30,5.77,Metropolitan Statistical Area,CA,"1,534,274","1,735,995","1,836,940","1,998,463"
53,Seattle - Tacoma - Bellevue,90,1547766900,54,47.6038,-122.3301,55.94,13.87,Metropolitan Statistical Area,WA,"2,559,136","3,043,934","3,439,806","3,867,046"
54,St. Louis,90,1547767560,93,38.6273,-90.1979,40.64,4.70,Metropolitan Statistical Area,MO-IL,"2,560,340","2,675,562","2,787,763","2,807,338"
55,Tampa - St. Petersburg - Clearwater (Tampa Bay...,90,1547768100,67,27.9478,-82.4585,68.00,3.36,Metropolitan Statistical Area,FL,"2,067,959","2,396,038","2,783,469","3,091,399"
56,Virginia Beach - Norfolk - Newport News (Hampt...,90,1547765940,67,36.8530,-75.9775,43.16,5.82,Metropolitan Statistical Area,VA-NC,"1,485,333","1,613,320","1,713,947","1,761,753"
57,Washington - Arlington - Alexandria,90,1547767980,69,38.8950,-77.0367,37.94,3.36,Metropolitan Statistical Area,DC-VA-MD-WV,"4,168,621","4,850,183","5,649,670","6,229,866"

In [ ]:
#drop duplicates keeping one with highest population